services:
  - type: web
    name: my-app
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
